### ISSUE TITLE
Error when Approving a record - Tsutomi 

### ISSUE THREAD

**Issue by kinosker** [HAS-CRM/IssueTracker#34]
Background:

User received an error when trying to approve a record at CRM
Quote Number: QSFIBU0000039

Below is the error log provided:

--------------------------------------------------------------------------------------------------------------------
Hi Irene,

I have an error on CRM system as below while I tried to approve 1 record.
Please cope with the situation.

Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: SecLib::AccessCheckEx failed. Returned hr = -2147187962, ObjectID: d1972136-d978-e711-9904-005056833f17, OwnerId: 5ae68742-1451-e511-9c41-005056831a76,  OwnerIdType: 8 and CallingUser: 8cb7e167-dc15-e711-90b7-005056831a76. ObjectTypeCode: 1084, objectBusinessUnitId: 735cde45-9f12-e711-90b7-005056831a76, AccessRights: WriteAccess Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ErrorCode>-2147187962</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>CallStack</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.MessageProcessor.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.InternalMessageDispatcher.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.ExternalMessageDispatcher.ExecuteInternal(IInProcessOrganizationServiceFactory serviceFactory, IPlatformMessageDispatcherFactory dispatcherFactory, String messageName, String requestName, Int32 primaryObjectTypeCode, Int32 secondaryObjectTypeCode, ParameterCollection fields, CorrelationToken correlationToken, CallerOriginToken originToken, UserAuth userAuth, Guid callerId, Guid transactionContextId, Int32 invocationSource, Nullable`1 requestId, Version endpointVersion)
   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.ExecuteRequest(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType)
   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType)</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <Message>SecLib::AccessCheckEx failed. Returned hr = -2147187962, ObjectID: d1972136-d978-e711-9904-005056833f17, OwnerId: 5ae68742-1451-e511-9c41-005056831a76,  OwnerIdType: 8 and CallingUser: 8cb7e167-dc15-e711-90b7-005056831a76. ObjectTypeCode: 1084, objectBusinessUnitId: 735cde45-9f12-e711-90b7-005056831a76, AccessRights: WriteAccess </Message>
  <Timestamp>2017-08-14T03:07:14.2646471Z</Timestamp>
  <InnerFault i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>

Regards,
Tsutomi
--------------------------------------------------------------------------------------------------------------------

**Comment by kinosker** [comment]
Prior to Tsutomi attempt to approve the quotation, it was already approved on 8th August 2017 by Yuji Sato.

![image](https://user-images.githubusercontent.com/8575807/29258257-c701f38a-80ea-11e7-893d-b03012afcad0.png)

**Comment by kinosker** [comment]
Diagnosis:
Replicated the error when clicking on activate quote instead of approve quote, as user does not have the access rights to modify quote.

Pending:
Whether user click on approve quote or activate quote.

-

**Comment by kinosker** [comment]
Closed:
User confirmed that she click on the activate quote button, which resulted in the error.
